/**
 * Curated half of the telemetry manifest.
 *
 * Everything here is a human decision that cannot be recovered from the data:
 * which Kusto table a file becomes, how its dates are written, and the window its
 * events must land in. The mechanical half — the column list and inferred types —
 * lives in `manifest.generated.ts` and is regenerated by
 * `scripts/generate-telemetry-manifest.ts`.
 *
 * The split matters. If the expected windows were derived from the data they would
 * match by construction and could never detect drift, which is precisely the
 * failure ADR 001 requires the bootstrap to catch.
 */

/**
 * How a file writes dates. The Training Lab does **not** use one convention:
 * applying any single format globally scatters the files across eight months
 * without raising an error (ADR 001, "Date formats are inconsistent per file").
 */
export type DateConvention =
  /** `4/16/2021, 9:09:00.730 AM` — US month-first with 12-hour clock. */
  | "us-long"
  /** `10/02/2026 11:00:12` — day-first. */
  | "dmy"
  /** `02/10/2026 10:23:22` — month-first. */
  | "mdy"
  /** `2026-02-08 09:12:34Z` / `2019-09-12T20:00:00.625Z`. */
  | "iso";

/** Kusto scalar types the loader emits. */
export type KustoType = "string" | "int" | "long" | "real" | "bool" | "datetime" | "dynamic";

export interface TelemetryColumn {
  name: string;
  type: KustoType;
}

/** Half-open `[from, to)` bound that every datetime value in a file must satisfy. */
export interface TimeWindow {
  from: string;
  to: string;
}

export interface TelemetryTable {
  /** Kusto table name. Not always the filename — see `SecurityEvents.csv`. */
  table: string;
  /**
   * Where the table's rows come from.
   *
   * `csv` tables are backed by a vendored file and get the full drift checks.
   * `generated` tables are produced at bootstrap — `SecurityAlert` is built
   * from detection rules and connector mappers, because the Training Lab ships
   * no alert data — so the file-backed checks do not apply to them.
   */
  source?: "csv" | "generated";
  /** Path relative to `fixtures/telemetry/`. Ignored for generated tables. */
  file: string;
  /** Row count excluding the header; a mismatch fails the bootstrap. */
  expectedRows: number;
  /** Absent when the file carries no parseable datetime column. */
  dateConvention?: DateConvention;
  /**
   * Era every datetime in the file must fall inside. Deliberately declared by
   * hand and kept tight enough that swapping DD/MM for MM/DD falls outside it.
   */
  expectedWindow?: TimeWindow;
  /** Applied after the generic ` [UTC]` header-suffix strip. */
  rename?: Record<string, string>;
  /**
   * Number of records the pinned upstream file is known to truncate, which the
   * parser right-pads. Pinning the count keeps the tolerance from hiding a new
   * defect. Omitted means zero, and zero is enforced.
   */
  knownShortRows?: number;
  columns: readonly TelemetryColumn[];
}

/** Curated per-file inputs, keyed by Kusto table name. */
export interface TableCuration {
  file: string;
  expectedRows: number;
  dateConvention?: DateConvention;
  expectedWindow?: TimeWindow;
  rename?: Record<string, string>;
  knownShortRows?: number;
}

/**
 * Portal exports suffix time columns with ` [UTC]`. The values are already UTC,
 * so the suffix is noise that would otherwise become part of the Kusto column
 * name and force every query to quote it.
 */
export const UTC_HEADER_SUFFIX = " [UTC]";

/**
 * Kusto rejects `-` in unquoted identifiers, and two upstream filenames contain
 * one (`sign-in_adelete_CL`, `solarigate-beacon-umbrella_CL`).
 */
export function toTableName(fileStem: string): string {
  return fileStem.replaceAll("-", "_");
}

/**
 * Coerces a CSV header into a plain Kusto identifier.
 *
 * Kusto's column naming rules are narrower than bracket-quoting suggests:
 * `['Blocked Categories']` is accepted but `['$table']` and `['Categories/0']`
 * are rejected outright as "does not comply with naming rules". Nine headers in
 * `solarigate-beacon-umbrella_CL.csv` hit this.
 *
 * Rather than quote the survivors and rewrite only the casualties, every column
 * is normalised to `[A-Za-z_][A-Za-z0-9_]*`. That keeps one rule instead of two,
 * and means no generated KQL — or agent-written KQL — ever needs bracket
 * quoting to read this data.
 */
export function sanitizeColumnName(raw: string): string {
  const replaced = raw.replaceAll(/[^A-Za-z0-9_]/g, "_");
  return /^[0-9]/.test(replaced) ? `_${replaced}` : replaced;
}

export const CURATION: Readonly<Record<string, TableCuration>> = {
  // --- BuildIn: real Microsoft table names -------------------------------------
  //
  // The 2021-04-16 Windows-log era. `SecurityEvents.csv` (plural) becomes
  // `SecurityEvent` (singular) because that is the real Log Analytics table an
  // analyst — and an agent trained on public KQL — will reach for.
  SecurityEvent: {
    file: "BuildIn/SecurityEvents.csv",
    expectedRows: 23_864,
    dateConvention: "us-long",
    expectedWindow: { from: "2021-04-16T00:00:00Z", to: "2021-04-17T00:00:00Z" },
    // ADR 001 mandate: the CSV has no TimeGenerated, and essentially every
    // realistic KQL query filters on it.
    rename: { TimeCollected: "TimeGenerated" },
    // The final record is a hand-appended EventID 1102 ("the audit log was
    // cleared") carrying a placeholder EventOriginId and a `pkwork` hostname
    // where the rest of the file is contoso-style. It stops one field short of
    // the header, omitting RelativeTargetName. Present in the pinned upstream
    // data; verified with an independent CSV parser, so it is theirs, not ours.
    knownShortRows: 1,
  },

  // The 2026-02-10 cross-source era.
  CommonSecurityLog: {
    file: "BuildIn/CommonSecurityLog.csv",
    expectedRows: 149,
    dateConvention: "dmy",
    expectedWindow: { from: "2026-02-10T00:00:00Z", to: "2026-02-11T00:00:00Z" },
  },
  AWSCloudTrail: {
    file: "BuildIn/AWSCloudTrail.csv",
    expectedRows: 47,
    dateConvention: "dmy",
    expectedWindow: { from: "2026-02-10T00:00:00Z", to: "2026-02-11T00:00:00Z" },
  },
  GCPAuditLogs: {
    file: "BuildIn/GCPAuditLogs.csv",
    expectedRows: 25,
    dateConvention: "dmy",
    expectedWindow: { from: "2026-02-10T00:00:00Z", to: "2026-02-11T00:00:00Z" },
  },

  // The 2026-02-06 CrowdStrike era. `dmy` is proven, not assumed:
  // CrowdStrikeHosts.FirstSeen contains `24/11/2025` and
  // CrowdStrikeVulnerabilities.CreatedTimestamp `25/01/2026`, both impossible
  // as MM/DD — they fail to parse under the wrong convention rather than
  // silently landing on the wrong date.
  CrowdStrikeAlerts: {
    file: "BuildIn/CrowdStrikeAlerts.csv",
    expectedRows: 53,
    dateConvention: "dmy",
    expectedWindow: { from: "2026-02-06T00:00:00Z", to: "2026-02-07T00:00:00Z" },
  },
  CrowdStrikeDetections: {
    file: "BuildIn/CrowdStrikeDetections.csv",
    expectedRows: 54,
    dateConvention: "dmy",
    expectedWindow: { from: "2026-02-06T00:00:00Z", to: "2026-02-07T00:00:00Z" },
  },
  CrowdStrikeCases: {
    file: "BuildIn/CrowdStrikeCases.csv",
    expectedRows: 1,
    dateConvention: "dmy",
    expectedWindow: { from: "2026-02-06T00:00:00Z", to: "2026-02-07T00:00:00Z" },
  },
  // Asset-inventory tables carry genuine history (first-seen, CVE publication),
  // so their windows open earlier than the scenario era.
  CrowdStrikeHosts: {
    file: "BuildIn/CrowdStrikeHosts.csv",
    expectedRows: 8,
    dateConvention: "dmy",
    expectedWindow: { from: "2025-01-01T00:00:00Z", to: "2026-02-07T00:00:00Z" },
  },
  CrowdStrikeVulnerabilities: {
    file: "BuildIn/CrowdStrikeVulnerabilities.csv",
    expectedRows: 10,
    dateConvention: "dmy",
    expectedWindow: { from: "2025-01-01T00:00:00Z", to: "2026-02-07T00:00:00Z" },
  },

  // --- Custom: _CL tables ------------------------------------------------------
  AzureActivity_CL: {
    file: "Custom/AzureActivity_CL.csv",
    expectedRows: 325,
    dateConvention: "us-long",
    expectedWindow: { from: "2021-04-26T00:00:00Z", to: "2021-04-27T00:00:00Z" },
  },
  OfficeActivity_CL: {
    file: "Custom/OfficeActivity_CL.csv",
    expectedRows: 266,
    dateConvention: "us-long",
    expectedWindow: { from: "2021-04-28T00:00:00Z", to: "2021-04-29T00:00:00Z" },
  },
  azureActivity_adele_CL: {
    file: "Custom/azureActivity_adele_CL.csv",
    expectedRows: 23,
    dateConvention: "us-long",
    expectedWindow: { from: "2021-04-28T00:00:00Z", to: "2021-04-29T00:00:00Z" },
  },
  sign_in_adelete_CL: {
    file: "Custom/sign-in_adelete_CL.csv",
    expectedRows: 56,
    dateConvention: "us-long",
    expectedWindow: { from: "2021-04-28T00:00:00Z", to: "2021-04-29T00:00:00Z" },
  },
  office_activity_inbox_rule_CL: {
    file: "Custom/office_activity_inbox_rule_CL.csv",
    expectedRows: 2,
    dateConvention: "us-long",
    expectedWindow: { from: "2021-04-26T00:00:00Z", to: "2021-04-27T00:00:00Z" },
  },
  OktaV2_CL: {
    file: "Custom/OktaV2_CL.csv",
    expectedRows: 36,
    dateConvention: "dmy",
    expectedWindow: { from: "2026-02-10T00:00:00Z", to: "2026-02-11T00:00:00Z" },
  },
  // The one genuinely ambiguous file: every row reads `02/10/2026`, so the
  // convention cannot be recovered from the file alone. ADR 001 resolves it to
  // MM/DD using SEG_MailGuard_CL's unambiguous ISO `2026-02-08` as an anchor —
  // under MM/DD it lands at 09:58-11:21 on 2026-02-10, interleaved with OktaV2_CL
  // and CommonSecurityLog on the same day. `expectedWindow` is the guard: read as
  // DD/MM this file jumps to October and the bootstrap fails.
  MailGuard365_Threats_CL: {
    file: "Custom/MailGuard365_Threats_CL.csv",
    expectedRows: 41,
    dateConvention: "mdy",
    expectedWindow: { from: "2026-02-10T00:00:00Z", to: "2026-02-11T00:00:00Z" },
  },
  SEG_MailGuard_CL: {
    file: "Custom/SEG_MailGuard_CL.csv",
    expectedRows: 5,
    dateConvention: "iso",
    expectedWindow: { from: "2026-02-08T00:00:00Z", to: "2026-02-09T00:00:00Z" },
  },
  // A third era, five years before the rest and not recorded in ADR 001's
  // original two-era table. One row.
  solarigate_beacon_umbrella_CL: {
    file: "Custom/solarigate-beacon-umbrella_CL.csv",
    expectedRows: 1,
    dateConvention: "iso",
    expectedWindow: { from: "2019-09-12T00:00:00Z", to: "2019-09-13T00:00:00Z" },
  },

  // No parseable datetime column at all, so no convention and no window.
  AuditLogsHunting_CL: { file: "Custom/AuditLogsHunting_CL.csv", expectedRows: 5 },
  disable_accounts_CL: { file: "Custom/disable_accounts_CL.csv", expectedRows: 4 },
  model_evasion_detection_CL: { file: "Custom/model_evasion_detection_CL.csv", expectedRows: 4 },
};
