#!/usr/bin/env bun
/* oxlint-disable eslint/no-await-in-loop --
 * Files are read one at a time on purpose: this is a developer tool whose
 * output is a reviewed diff, and processing 21 files in order keeps the
 * progress log readable and the generated ordering stable.
 */
/**
 * Regenerates `apps/mock-sentinel/src/telemetry/manifest.generated.ts` from the
 * vendored CSVs plus the curated inputs in `manifest.ts`.
 *
 * Run this when the pinned upstream revision changes — an upstream update is an
 * explicit dependency upgrade (ADR 001, "Determinism"), and the regenerated diff
 * is the schema review step of that upgrade.
 *
 *     bun run data:manifest
 *
 * Types are inferred conservatively. Anything that is not unambiguously a
 * datetime, number, boolean or JSON document stays `string`, because a wrong
 * type does not fail the ingest — it silently nulls the column. The bootstrap's
 * null-rate check exists to catch whatever slips through anyway.
 */

import { parseCsv } from "../apps/mock-sentinel/src/telemetry/csv.ts";
import { CURATION, type KustoType } from "../apps/mock-sentinel/src/telemetry/manifest.ts";
import {
  normalizeHeader,
  tryParseDateTime,
} from "../apps/mock-sentinel/src/telemetry/normalize.ts";
import { TELEMETRY_DIR, readTelemetryFile } from "../apps/mock-sentinel/src/telemetry/source.ts";

const INTEGER = /^-?\d+$/;
const REAL = /^-?(?:\d+\.\d*|\.\d+|\d+)(?:[eE][-+]?\d+)?$/;

function isJsonDocument(value: string): boolean {
  const t = value.trim();
  if (!t.startsWith("{") && !t.startsWith("[")) return false;
  try {
    JSON.parse(t);
    return true;
  } catch {
    return false;
  }
}

function inferType(
  values: string[],
  convention: Parameters<typeof tryParseDateTime>[1] | undefined,
): KustoType {
  if (values.length === 0) return "string";

  if (convention !== undefined && values.every((v) => tryParseDateTime(v, convention) !== null)) {
    return "datetime";
  }
  if (values.every((v) => /^(true|false)$/i.test(v.trim()))) return "bool";

  if (values.every((v) => INTEGER.test(v.trim()))) {
    // A leading zero is a formatted identifier, not a number; typing it numeric
    // would silently drop the zero.
    const significant = values.map((v) => v.trim()).filter((v) => v !== "0" && v !== "-0");
    const hasLeadingZero = significant.some((v) => /^-?0\d/.test(v));
    if (!hasLeadingZero) {
      const nums = values.map((v) => Number(v.trim()));
      if (nums.every((n) => Number.isSafeInteger(n))) {
        return nums.every((n) => n >= -2_147_483_648 && n <= 2_147_483_647) ? "int" : "long";
      }
    }
    return "string";
  }
  if (values.every((v) => REAL.test(v.trim()))) return "real";
  if (values.every(isJsonDocument)) return "dynamic";
  return "string";
}

const entries = Object.entries(CURATION).toSorted(([a], [b]) => a.localeCompare(b));
const blocks: string[] = [];
let totalColumns = 0;

for (const [table, curation] of entries) {
  const csv = parseCsv(await readTelemetryFile(curation.file), curation.file);
  const header = normalizeHeader(csv.header, curation.rename);

  // Sanitisation maps a wider alphabet onto plain identifiers, so it can in
  // principle merge two distinct source columns into one. It does not today,
  // and this is what notices if an upstream revision changes that.
  const collisions = header.filter((name, i) => header.indexOf(name) !== i);
  if (collisions.length > 0) {
    throw new Error(
      `${curation.file}: column names collide after sanitisation: ${[...new Set(collisions)].join(", ")}`,
    );
  }

  const columns = header.map((name, index) => {
    const values = csv.rows.map((row) => row[index] ?? "").filter((v) => v.trim() !== "");
    return { name, type: inferType(values, curation.dateConvention) };
  });

  totalColumns += columns.length;
  const dateCount = columns.filter((c) => c.type === "datetime").length;
  console.info(
    `${table.padEnd(32)} ${String(columns.length).padStart(3)} cols, ${String(dateCount).padStart(2)} datetime`,
  );

  const rendered = columns
    .map((c) => `    { name: ${JSON.stringify(c.name)}, type: "${c.type}" },`)
    .join("\n");
  blocks.push(`  ${JSON.stringify(table)}: [\n${rendered}\n  ],`);
}

const output = `/* eslint-disable */
// Generated by scripts/generate-telemetry-manifest.ts — do not edit by hand.
//
// Column names and types derived from the vendored Training Lab CSVs at the
// pinned upstream revision (see fixtures/telemetry/SOURCE.md). Only columns
// actually present in the source data appear here: ADR 001 rules out padding
// tables out to the full ~230-column Sentinel schema, because GET /schema feeds
// the agent's startup context and permanently-null columns are pure noise.
//
// Regenerate with: bun run data:manifest

import type { TelemetryColumn } from "./manifest.ts";

export const GENERATED_COLUMNS: Readonly<Record<string, readonly TelemetryColumn[]>> = {
${blocks.join("\n")}
};
`;

const target = new URL(
  "../apps/mock-sentinel/src/telemetry/manifest.generated.ts",
  import.meta.url,
);
await Bun.write(target, output);

console.info(`\n${entries.length} tables, ${totalColumns} columns -> ${target.pathname}`);
console.info(`source: ${TELEMETRY_DIR}`);
